### ISSUE TITLE
do not split if resulting node would have zero elements

### ISSUE THREAD

**Issue by falkben** [neurodata/R-RerF#106]
On i386/windows the following code from `testpredictions` resulted in at least one tree being generated which had a node of zero elements.  

```r
forest <- RerF(X, Y,
    seed = 1L, num.cores = 1L, store.oob = TRUE, min.parent = 1,
    max.depth = 0
  )
  oob.predictions <- OOBPredict(X, forest, num.cores = 1L)
```

We have a temporary fix for this in https://github.com/neurodata/R-RerF/pull/105 but a better solution would be to ensure we never split when the result would be a node with zero elements.

**Comment by MrAE** [comment]
Before all of the c++ code is merged into R-RerF this issue should stick around. 
After the c++ (fast-RerF) code has been completely merged in we should be safe to close this issue. 
@falkben I'm moving this out of Sprint II for now.

**Comment by MrAE** [comment]
James found that this problem originates from checking if two floats are equal using `==` instead of properly checking within machine epsilon. The fix should be implemented in `split.cpp` and the following lines should be removed from `BuildTree.R`.
https://github.com/neurodata/R-RerF/blob/05faa9634ad5f0c849c04e8c97c61e1aa49d53ff/R/BuildTree.R#L271-L283

**Comment by falkben** [comment]
fixed in https://github.com/neurodata/R-RerF/pull/149
