### ISSUE TITLE
Randomly assign predictions when ClassProb has ties

### ISSUE THREAD

**Issue by j1c** [neurodata/R-RerF#48]
Currently, it just chooses the class with lowest index when there are ties.

**Comment by jovo** [comment]
actually, we should output for that tree the posterior per class, which is going to be 0.5 if there are ties between 2 classes.

@ttomita @jbrowne6 currently, when we aggregate over trees, do we average the maximum a posteriori class, or do we have the posterior probability of being in each class?

this corner case illustrates an advantage to averaging posteriors.
also, if we are trying to estimate posterior rather than class, 
i believe our estimates will be more accurate if we average posteriors.

**Comment by jovo** [comment]
once we fix https://github.com/neurodata/R-RerF/issues/53
this issue is automatically resolved
